/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_example_com_testjni6_JNITest */

#ifndef _Included_jni_example_com_testjni6_JNITest
#define _Included_jni_example_com_testjni6_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_example_com_testjni6_JNITest
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_example_com_testjni6_JNITest_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
