/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_example_com_testjni6_AESUtil */

#ifndef _Included_jni_example_com_testjni6_AESUtil
#define _Included_jni_example_com_testjni6_AESUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_example_com_testjni6_AESUtil
 * Method:    encrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_example_com_testjni6_AESUtil_encrypt
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     jni_example_com_testjni6_AESUtil
 * Method:    decrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_example_com_testjni6_AESUtil_decrypt
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
